use crate::{
    engine::{build_personal_demo, compare_playlists},
    genre::normalize_genres,
    models::{DemoPayload, Playlist, Track, VersionType},
    normalize::normalize_text,
};
use std::{
    collections::HashMap,
    time::{SystemTime, UNIX_EPOCH},
};

fn track(
    id: &str,
    title: &str,
    artist: &str,
    album: &str,
    genres: &[&str],
    year: u16,
    language: &str,
    energy: f32,
    mood: &[&str],
) -> Track {
    Track {
        id: id.into(),
        title: title.into(),
        normalized_title: normalize_text(title),
        artists: vec![artist.into()],
        album: Some(album.into()),
        genres: normalize_genres(genres.iter()),
        release_year: Some(year),
        language: Some(language.into()),
        duration_ms: Some(220_000),
        platform: "demo".into(),
        platform_url: Some(format!(
            "https://open.spotify.com/search/{}",
            urlencoding::encode(&format!("{artist} {title}"))
        )),
        external_ids: HashMap::new(),
        version_type: VersionType::Original,
        mood_tags: mood.iter().map(|v| (*v).into()).collect(),
        energy_score: Some(energy),
        popularity: Some(0.55),
        metadata_confidence: 0.88,
    }
}

pub fn demo_playlists() -> Vec<Playlist> {
    vec![
        Playlist {
            id: "demo-a".into(),
            name: "Seoul after midnight".into(),
            owner_label: "用户 A".into(),
            source: "内置 Demo 数据".into(),
            is_demo: true,
            tracks: vec![
                track(
                    "a1",
                    "Kazino",
                    "BIBI",
                    "Life is a Bi...",
                    &["Korean R&B", "K-pop"],
                    2020,
                    "韩语",
                    0.53,
                    &["夜色", "克制"],
                ),
                track(
                    "a2",
                    "instagram",
                    "DEAN",
                    "instagram",
                    &["Korean R&B", "Alternative R&B"],
                    2017,
                    "韩语",
                    0.43,
                    &["内省", "都市"],
                ),
                track(
                    "a3",
                    "NAPPA",
                    "Crush",
                    "NAPPA",
                    &["Korean R&B", "Neo Soul"],
                    2019,
                    "韩语",
                    0.58,
                    &["温暖", "松弛"],
                ),
                track(
                    "a4",
                    "Happen",
                    "Heize",
                    "HAPPEN",
                    &["Korean R&B", "K-pop"],
                    2021,
                    "韩语",
                    0.49,
                    &["怀旧", "细腻"],
                ),
                track(
                    "a5",
                    "No Make Up",
                    "Zion.T",
                    "OO",
                    &["Korean R&B", "Neo Soul"],
                    2015,
                    "韩语",
                    0.47,
                    &["温暖", "轻盈"],
                ),
                track(
                    "a6",
                    "WA-R-R",
                    "Colde",
                    "Love Part 1",
                    &["Korean R&B", "Indie"],
                    2019,
                    "韩语",
                    0.39,
                    &["平静", "柔和"],
                ),
                track(
                    "a7",
                    "Plastic Love",
                    "Mariya Takeuchi",
                    "VARIETY",
                    &["City Pop", "Japanese Pop"],
                    1984,
                    "日语",
                    0.62,
                    &["复古", "夜色"],
                ),
                track(
                    "a8",
                    "Midnight Pretenders",
                    "Tomoko Aran",
                    "Fuyukukan",
                    &["City Pop", "Japanese Pop"],
                    1983,
                    "日语",
                    0.55,
                    &["复古", "梦幻"],
                ),
            ],
        },
        Playlist {
            id: "demo-b".into(),
            name: "Guitars & rainy windows".into(),
            owner_label: "用户 B".into(),
            source: "内置 Demo 数据".into(),
            is_demo: true,
            tracks: vec![
                track(
                    "b1",
                    "Do I Wanna Know?",
                    "Arctic Monkeys",
                    "AM",
                    &["Indie Rock", "Alternative Rock"],
                    2013,
                    "英语",
                    0.71,
                    &["暗色", "张力"],
                ),
                track(
                    "b2",
                    "There Is a Light That Never Goes Out",
                    "The Smiths",
                    "The Queen Is Dead",
                    &["Indie Rock", "Britpop"],
                    1986,
                    "英语",
                    0.68,
                    &["浪漫", "怀旧"],
                ),
                track(
                    "b3",
                    "No Surprises",
                    "Radiohead",
                    "OK Computer",
                    &["Alternative Rock", "Art Rock"],
                    1997,
                    "英语",
                    0.48,
                    &["克制", "忧郁"],
                ),
                track(
                    "b4",
                    "Supersonic",
                    "Oasis",
                    "Definitely Maybe",
                    &["Britpop", "Rock"],
                    1994,
                    "英语",
                    0.83,
                    &["昂扬", "直接"],
                ),
                track(
                    "b5",
                    "Someday",
                    "The Strokes",
                    "Is This It",
                    &["Indie Rock", "Garage Rock"],
                    2001,
                    "英语",
                    0.74,
                    &["明亮", "怀旧"],
                ),
                track(
                    "b6",
                    "Chocolate",
                    "The 1975",
                    "The 1975",
                    &["Indie Pop", "Alternative"],
                    2013,
                    "英语",
                    0.82,
                    &["青春", "明亮"],
                ),
                track(
                    "b7",
                    "My Number",
                    "Foals",
                    "Holy Fire",
                    &["Indie Rock", "Dance Rock"],
                    2013,
                    "英语",
                    0.88,
                    &["律动", "明亮"],
                ),
                track(
                    "b8",
                    "Dreams",
                    "The Cranberries",
                    "Everybody Else Is Doing It, So Why Can't We?",
                    &["Alternative", "Dream Pop"],
                    1993,
                    "英语",
                    0.61,
                    &["梦幻", "轻盈"],
                ),
            ],
        },
        Playlist {
            id: "demo-c".into(),
            name: "旧唱片与晚风".into(),
            owner_label: "用户 C".into(),
            source: "内置 Demo 数据".into(),
            is_demo: true,
            tracks: vec![
                track(
                    "c1",
                    "橄榄树",
                    "齐豫",
                    "橄榄树",
                    &["华语民谣", "经典华语"],
                    1979,
                    "国语",
                    0.32,
                    &["怀旧", "辽阔"],
                ),
                track(
                    "c2",
                    "外面的世界",
                    "齐秦",
                    "冬雨",
                    &["华语流行", "民谣"],
                    1987,
                    "国语",
                    0.40,
                    &["怀旧", "温暖"],
                ),
                track(
                    "c3",
                    "恋曲1990",
                    "罗大佑",
                    "爱人同志",
                    &["华语流行", "民谣"],
                    1988,
                    "国语",
                    0.38,
                    &["叙事", "怀旧"],
                ),
                track(
                    "c4",
                    "红豆",
                    "王菲",
                    "唱游",
                    &["华语流行", "经典华语"],
                    1998,
                    "国语",
                    0.36,
                    &["细腻", "平静"],
                ),
                track(
                    "c5",
                    "成都",
                    "赵雷",
                    "无法长大",
                    &["华语民谣", "民谣"],
                    2016,
                    "国语",
                    0.41,
                    &["城市", "温暖"],
                ),
                track(
                    "c6",
                    "一荤一素",
                    "毛不易",
                    "平凡的一天",
                    &["华语流行", "民谣"],
                    2018,
                    "国语",
                    0.34,
                    &["家庭", "温暖"],
                ),
            ],
        },
    ]
}

pub fn catalog() -> Vec<Track> {
    vec![
        track(
            "r1",
            "Tadow",
            "Masego & FKJ",
            "Lady Lady",
            &["Neo Soul", "Jazz R&B"],
            2018,
            "英语",
            0.63,
            &["松弛", "夜色"],
        ),
        track(
            "r2",
            "Square (2017)",
            "Yerin Baek",
            "Every letter I sent you.",
            &["Korean R&B", "Indie Pop"],
            2019,
            "英语",
            0.47,
            &["细腻", "温暖"],
        ),
        track(
            "r3",
            "D (Half Moon)",
            "DEAN",
            "130 mood : TRBL",
            &["Korean R&B", "Alternative R&B"],
            2016,
            "韩语",
            0.52,
            &["夜色", "轻盈"],
        ),
        track(
            "r4",
            "Get You",
            "Daniel Caesar",
            "Freudian",
            &["Neo Soul", "R&B"],
            2017,
            "英语",
            0.46,
            &["温暖", "浪漫"],
        ),
        track(
            "r5",
            "Japanese Denim",
            "Daniel Caesar",
            "Japanese Denim",
            &["Neo Soul", "R&B"],
            2016,
            "英语",
            0.39,
            &["温暖", "平静"],
        ),
        track(
            "r6",
            "Make It Better",
            "Anderson .Paak",
            "Ventura",
            &["Neo Soul", "Funk"],
            2019,
            "英语",
            0.66,
            &["明亮", "律动"],
        ),
        track(
            "r7",
            "Cranes in the Sky",
            "Solange",
            "A Seat at the Table",
            &["Neo Soul", "Art Pop"],
            2016,
            "英语",
            0.41,
            &["克制", "辽阔"],
        ),
        track(
            "r8",
            "Sober",
            "Childish Gambino",
            "Kauai",
            &["Alternative R&B", "Psychedelic Soul"],
            2014,
            "英语",
            0.70,
            &["迷幻", "律动"],
        ),
        track(
            "r9",
            "Them Changes",
            "Thundercat",
            "The Beyond / Where the Giants Roam",
            &["Jazz-Funk", "Neo Soul"],
            2015,
            "英语",
            0.78,
            &["灵动", "迷幻"],
        ),
        track(
            "r10",
            "Pink + White",
            "Frank Ocean",
            "Blonde",
            &["Alternative R&B", "Art Pop"],
            2016,
            "英语",
            0.49,
            &["梦幻", "温暖"],
        ),
        track(
            "br1",
            "Dreams",
            "The Cranberries",
            "Everybody Else Is Doing It, So Why Can't We?",
            &["Alternative", "Dream Pop"],
            1993,
            "英语",
            0.61,
            &["梦幻", "轻盈"],
        ),
        track(
            "br2",
            "Electric Feel",
            "MGMT",
            "Oracular Spectacular",
            &["Indie Pop", "Psychedelic Pop"],
            2007,
            "英语",
            0.77,
            &["迷幻", "律动"],
        ),
        track(
            "br3",
            "The Less I Know the Better",
            "Tame Impala",
            "Currents",
            &["Psychedelic Pop", "Indie Rock", "Funk"],
            2015,
            "英语",
            0.74,
            &["迷幻", "律动"],
        ),
        track(
            "br4",
            "505",
            "Arctic Monkeys",
            "Favourite Worst Nightmare",
            &["Indie Rock", "Alternative Rock"],
            2007,
            "英语",
            0.76,
            &["张力", "夜色"],
        ),
        track(
            "br5",
            "Somebody Else",
            "The 1975",
            "I like it when you sleep...",
            &["Indie Pop", "Alternative R&B"],
            2016,
            "英语",
            0.58,
            &["夜色", "克制"],
        ),
    ]
}

pub fn demo_payload() -> DemoPayload {
    let lists = demo_playlists();
    let personal = build_personal_demo(lists[0].clone());
    let comparison = compare_playlists(&lists[0], &lists[1]);
    let epoch = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();
    DemoPayload {
        generated_at: format!("unix:{epoch}"),
        disclosure: "本页音乐元数据、推荐和匹配为内置离线 Demo；没有读取或修改任何真实音乐账号。"
            .into(),
        personal,
        comparison,
        available_playlists: lists,
    }
}
